import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
export const MM_TO_PT = 72 / 25.4;

export interface FieldMeta {
  type: 'grid' | 'text' | 'checkbox';
  x: number;
  y: number;
  width?: number;
  height?: number;
  boxes?: number;
  box_width?: number;
  data_field?: string;
  match?: string;
  transform?: string;
}

export class PanPdfEngine {
  private pdfDoc!: PDFDocument;
  private font!: any;
  private dingbats!: any;
  private config: Record<string, Record<string, FieldMeta>>;

  constructor(config: Record<string, Record<string, FieldMeta>>) {
    this.config = config;
  }

  async init(templateBuffer: ArrayBuffer | Uint8Array) {
    this.pdfDoc = await PDFDocument.load(templateBuffer);
    this.font = await this.pdfDoc.embedFont(StandardFonts.Helvetica);
    this.dingbats = await this.pdfDoc.embedFont(StandardFonts.ZapfDingbats);
  }

  async generate(data: Record<string, string>, isCorrection: boolean = false, watermark: boolean = false): Promise<Uint8Array> {
    const pages = this.pdfDoc.getPages();

    // Safety check for correction mode
    if (isCorrection && !data.old_pan) {
      throw new Error("STRICT ENGINE BLOCK: oldPan is mandatory in correction mode.");
    }

    // Process page 1
    if (this.config.page1 && pages[0]) {
      this.renderFields(pages[0], this.config.page1, data);
      if (watermark) await this.drawWatermark(pages[0]);
    }

    // Process page 2
    if (this.config.page2 && pages[1]) {
      this.renderFields(pages[1], this.config.page2, data);
      if (watermark) await this.drawWatermark(pages[1]);
    }

    return await this.pdfDoc.save();
  }

  private async drawWatermark(page: any) {
    const { width, height } = page.getSize();

    // 2. Draw "PANTRA" text — center diagonal
    const watermarkText = "PANTRA";
    const fontSize = 65;
    
    page.drawText(watermarkText, {
      x: width * 0.20,
      y: height * 0.45,
      size: fontSize,
      font: this.font,
      color: rgb(0, 0, 0),
      opacity: 0.3,
      rotate: { angle: -30, type: 'degrees' as any },
    });

    // 3. Second watermark text — upper area for coverage
    page.drawText(watermarkText, {
      x: width * 0.35,
      y: height * 0.75,
      size: fontSize,
      font: this.font,
      color: rgb(0, 0, 0),
      opacity: 0.2,
      rotate: { angle: -30, type: 'degrees' as any },
    });

    // 4. Small footnote
    page.drawText("Generated by PANTRA – Upgrade for watermark-free PDF", {
      x: 50,
      y: 50,
      size: 10,
      font: this.font,
      color: rgb(0.4, 0.4, 0.4),
      opacity: 0.5,
    });
  }

  private renderFields(page: any, fields: Record<string, FieldMeta>, data: Record<string, any>) {
    const pageHeight = page.getHeight();

    for (const [fieldKey, meta] of Object.entries(fields)) {
      const dataKey = meta.data_field || fieldKey;
      let value = data[dataKey];

      if (value === undefined || value === null) continue;

      switch (meta.type) {
        case 'grid':
          // Convert to string and sanitise if it hasn't been done by mapping layer
          const text = String(value);
          this.drawGridText(page, text, meta, pageHeight);
          break;
        case 'text':
          this.drawText(page, String(value), meta, pageHeight);
          break;
        case 'checkbox':
          this.drawCheckbox(page, String(value), meta, pageHeight);
          break;
      }
    }
  }

  private drawGridText(page: any, text: string, meta: FieldMeta, pageHeight: number) {
    if (!text) return;
    
    // The engine purely handles coordinates and box placement
    // Mapping Layer (text-mapper) is responsible for sanitization
    const chars = text.toUpperCase().replace(/[^A-Z0-9 ]/g, "").split('').slice(0, meta.boxes || 25);
    
    const boxWidthPt = (meta.box_width || 5.42) * MM_TO_PT;
    const startXPt = meta.x * MM_TO_PT;
    const heightPt = (meta.height || 4.2) * MM_TO_PT;
    const bottomYPt = pageHeight - ((meta.y * MM_TO_PT) + heightPt);
    
    const fontSize = 10;

    chars.forEach((char, index) => {
      if (char === ' ') return;

      const xPt = startXPt + (index * boxWidthPt);
      
      const textWidth = this.font.widthOfTextAtSize(char, fontSize);
      const xOffset = (boxWidthPt - textWidth) / 2;

      page.drawText(char, {
        x: xPt + xOffset,
        y: bottomYPt + (heightPt * 0.2), // Adjust vertical baseline
        size: fontSize,
        font: this.font,
        color: rgb(0, 0, 0),
      });
    });
  }

  private drawText(page: any, text: string, meta: FieldMeta, pageHeight: number) {
    if (!text) return;
    
    const xPt = meta.x * MM_TO_PT;
    const heightPt = (meta.height || 4.2) * MM_TO_PT;
    const bottomYPt = pageHeight - ((meta.y * MM_TO_PT) + heightPt);
    const fontSize = 10;

    page.drawText(text, {
        x: xPt,
        y: bottomYPt + 3, 
        size: fontSize,
        font: this.font,
        color: rgb(0, 0, 0),
    });
  }

  private drawCheckbox(page: any, value: string, meta: FieldMeta, pageHeight: number) {
    // Only check if value exactly matches the configured match value
    if (!value || value !== meta.match) return;

    const xPt = meta.x * MM_TO_PT;
    const heightPt = (meta.height || 3.5) * MM_TO_PT;
    const bottomYPt = pageHeight - ((meta.y * MM_TO_PT) + heightPt);
    
    // Size slightly smaller than box to fit
    const fontSize = 10; 

    // The unicode for checkmark in ZapfDingbats is usually \u2714
    page.drawText('\u2714', {
      x: xPt + 1.5, // slight horizontal padding
      y: bottomYPt + 1.5, // slight vertical padding
      size: fontSize,
      font: this.dingbats,
      color: rgb(0, 0, 0),
    });
  }
}
